import 'dart:math';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:sound_effect/sound_effect.dart';

/// Board sounds, generated by `tool/make_sounds.py`: each in a few takes,
/// picked at random so repeated moves don't sound mechanical.
enum GameSound {
  /// The piece's felt base sliding while it travels.
  glide,

  /// A piece landing.
  move,
  capture,
  castle,
  check;

  static const takes = 3;

  String asset(int take) => 'assets/sounds/${name}_$take.wav';
}

/// Plays [GameSound]s. Behind an interface so tests can use a silent fake.
abstract interface class SoundPlayer {
  void play(GameSound sound);
}

/// Low-latency playback via `sound_effect` (the Lichess plugin). Sounds load
/// in the background on first use; failures are ignored, since a missing
/// sound should never interrupt a game.
class SoundEffectPlayer implements SoundPlayer {
  SoundEffectPlayer() {
    _ready = _load();
  }

  final _plugin = SoundEffect();
  final _random = Random();
  late final Future<bool> _ready;

  /// The take each sound played last, so the next one differs.
  final _lastTake = <GameSound, int>{};

  Future<bool> _load() async {
    try {
      // Up to 4 at once, so a quick capture-then-check doesn't cut off.
      await _plugin.initialize(maxStreams: 4);
      for (final sound in GameSound.values) {
        for (var take = 1; take <= GameSound.takes; take++) {
          await _plugin.load('${sound.name}_$take', sound.asset(take));
        }
      }
      return true;
    } catch (_) {
      return false;
    }
  }

  @override
  void play(GameSound sound) {
    _ready.then((ready) {
      if (!ready) return;
      // Any take but the last one.
      final last = _lastTake[sound];
      var take = 1 + _random.nextInt(GameSound.takes - (last == null ? 0 : 1));
      if (last != null && take >= last) take++;
      _lastTake[sound] = take;
      _plugin.play('${sound.name}_$take').catchError((_) {});
    });
  }
}

final soundPlayerProvider = Provider<SoundPlayer>((ref) => SoundEffectPlayer());
